#!/usr/bin/env python3
# gen_lut.py - generates sin_lut.h
import math
import sys

LUT_BITS = 10
LUT_SIZE = 1 << LUT_BITS
FIX_BITS = 16
FIX_ONE = 1 << FIX_BITS

def main(out=sys.stdout):
    w = out.write
    w("// sin_lut.h - generated by gen_lut.py, do not edit\n")
    w("#ifndef SIN_LUT_H\n")
    w("#define SIN_LUT_H\n\n")
    w("#include <stdint.h>\n")
    w("#include <GL/fixed.h>\n\n")
    w(f"#define SIN_LUT_BITS {LUT_BITS}\n")
    w(f"#define SIN_LUT_SIZE {LUT_SIZE}\n")
    w(f"#define SIN_LUT_MASK (SIN_LUT_SIZE - 1)\n\n")

    w("static const GLfixed sin_lut[SIN_LUT_SIZE] = {\n")
    per_line = 4
    for i in range(0, LUT_SIZE, per_line):
        vals = []
        for j in range(per_line):
            value = math.sin(2.0 * math.pi * (i + j) / LUT_SIZE)
            vals.append(f"{int(round(value * FIX_ONE)):+d}")
        w("    " + ", ".join(vals) + ",\n")
    w("};\n\n")

    # Inline helpers. Cosine = sine shifted by quarter period.
    w("static inline GLfixed sin_lut_lookup(uint32_t phase) {\n")
    w("    // phase is a full 32-bit phase accumulator; wraps naturally\n")
    w("    uint32_t idx = phase >> (32 - SIN_LUT_BITS);\n")
    w("    return sin_lut[idx & SIN_LUT_MASK];\n")
    w("}\n\n")

    w("static inline GLfixed cos_lut_lookup(uint32_t phase) {\n")
    w("    uint32_t idx = (phase >> (32 - SIN_LUT_BITS)) + (SIN_LUT_SIZE / 4);\n")
    w("    return sin_lut[idx & SIN_LUT_MASK];\n")
    w("}\n\n")

    # Linearly-interpolated versions, much more accurate for the same table size
    w("static inline GLfixed sin_lut_lerp(uint32_t phase) {\n")
    w("    uint32_t idx  = phase >> (32 - SIN_LUT_BITS);\n")
    w("    uint32_t frac_bits = 32 - SIN_LUT_BITS;\n")
    w("    int64_t frac = phase & ((1u << frac_bits) - 1u);\n")
    w("    GLfixed a = sin_lut[idx & SIN_LUT_MASK];\n")
    w("    GLfixed b = sin_lut[(idx + 1) & SIN_LUT_MASK];\n")
    w("    return a + (GLfixed)(((b - a) * frac) >> frac_bits);\n")
    w("}\n\n")

    w("static inline GLfixed cos_lut_lerp(uint32_t phase) {\n")
    w("    return sin_lut_lerp(phase + (1u << (32 - 2)));\n")
    w("}\n\n")

    w("static inline uint32_t sin_lut_phase_from_radians(GLfixed r) {\n")
    w("    r %= TGL_FIX_2PI;\n")
    w("    return (uint32_t)((r * ((int64_t)1 << 32)) / TGL_FIX_2PI);\n")
    w("}\n\n")

    w("#endif // SIN_LUT_H\n")

if __name__ == "__main__":
    main()
