#!/usr/bin/env python3
# gen_lut.py - generates sin_lut.h
import math
import sys

LUT_BITS = 10
LUT_SIZE = 1 << LUT_BITS

def main(out=sys.stdout):
    w = out.write
    w("// sin_lut.h - generated by gen_lut.py, do not edit\n")
    w("#ifndef SIN_LUT_H\n")
    w("#define SIN_LUT_H\n\n")
    w("#include <stdint.h>\n\n")
    w(f"#define SIN_LUT_BITS {LUT_BITS}\n")
    w(f"#define SIN_LUT_SIZE {LUT_SIZE}\n")
    w(f"#define SIN_LUT_MASK (SIN_LUT_SIZE - 1)\n\n")

    w("static const double sin_lut[SIN_LUT_SIZE] = {\n")
    per_line = 4
    for i in range(0, LUT_SIZE, per_line):
        vals = [
            f"{math.sin(2.0 * math.pi * (i + j) / LUT_SIZE):+.17e}"
            for j in range(per_line)
        ]
        w("    " + ", ".join(vals) + ",\n")
    w("};\n\n")

    # Inline helpers. Cosine = sine shifted by quarter period.
    w("static inline double sin_lut_lookup(uint32_t phase) {\n")
    w("    // phase is a full 32-bit phase accumulator; wraps naturally\n")
    w("    uint32_t idx = phase >> (32 - SIN_LUT_BITS);\n")
    w("    return sin_lut[idx & SIN_LUT_MASK];\n")
    w("}\n\n")

    w("static inline double cos_lut_lookup(uint32_t phase) {\n")
    w("    uint32_t idx = (phase >> (32 - SIN_LUT_BITS)) + (SIN_LUT_SIZE / 4);\n")
    w("    return sin_lut[idx & SIN_LUT_MASK];\n")
    w("}\n\n")

    # Linearly-interpolated versions, much more accurate for the same table size
    w("static inline double sin_lut_lerp(uint32_t phase) {\n")
    w("    uint32_t idx  = phase >> (32 - SIN_LUT_BITS);\n")
    w("    uint32_t frac_bits = 32 - SIN_LUT_BITS;\n")
    w("    double frac = (phase & ((1u << frac_bits) - 1u)) * (1.0 / (1u << frac_bits));\n")
    w("    double a = sin_lut[idx & SIN_LUT_MASK];\n")
    w("    double b = sin_lut[(idx + 1) & SIN_LUT_MASK];\n")
    w("    return a + (b - a) * frac;\n")
    w("}\n\n")

    w("static inline double cos_lut_lerp(uint32_t phase) {\n")
    w("    return sin_lut_lerp(phase + (1u << (32 - 2)));\n")
    w("}\n\n")

    # Convenience: radians -> phase. Handy but slower (uses fmod-like behavior via cast).
    w("static inline uint32_t sin_lut_phase_from_radians(double r) {\n")
    w("    // Maps radians to 32-bit phase. 2*pi -> 2^32.\n")
    w("    const double scale = 4294967296.0 / (2.0 * 3.14159265358979323846);\n")
    w("    return (uint32_t)(int64_t)(r * scale);\n")
    w("}\n\n")

    w("#endif // SIN_LUT_H\n")

if __name__ == "__main__":
    main()
